### ISSUE TITLE
something missing in the code

### ISSUE THREAD

**Issue by Clown1206** [lujiaming-12138/DuaLight#1]
Hello, thank you for providing the open source code, but there is something missing in the code, such as tsc.utils,tsc.multi_agent。

**Comment by lujiaming-12138** [comment]
Thank you for your feedback. I will find a new machine to test the operation of the code and give you feedback within a week.

**Comment by lujiaming-12138** [comment]
Due to negligence, two important files are indeed missing. We have added the missing files in the latest code. I will close this issue. Thank you.
