### ISSUE TITLE
The version of libsumo

### ISSUE THREAD

**Issue by way-thu** [lujiaming-12138/DuaLight#2]
Hello, thanks for your sharing, I try to run this code on my computer, but something wrong occurs.  

I want to know what the version of libsumo, sumolib and traci.  I tried libsumo 1.12 and lower, the error likes below
![image](https://github.com/lujiaming-12138/DuaLight/assets/113359869/6fb6bbe5-451a-4554-8841-2382f0a0ed78)

I changed libsumo to 1.20, and the error likes below
![image](https://github.com/lujiaming-12138/DuaLight/assets/113359869/23752a97-cc6e-4bc9-ac5b-69e7578136dd)

It has bothered me for a long time, I really hope to hear your reply.  Much thanks!

**Comment by lujiaming-12138** [comment]
Hello,

Thanks for reaching out! Here is my Python package list:

- absl-py 1.4.0
- astor 0.8.1
- certifi 2020.6.20
- cycler 0.11.0
- dataclasses 0.8
- decorator 4.4.2
- eclipse-sumo 1.14.0
- future 0.18.3
- gast 0.5.4
- grpcio 1.48.2
- h5py 2.10.0
- importlib-metadata 4.8.3
- Keras 2.1.0
- Keras-Applications 1.0.8
- Keras-Preprocessing 1.1.2
- kiwisolver 1.3.1
- libsumo 1.16.0
- Markdown 3.3.7
- matplotlib 3.3.4
- networkx 2.5.1
- numpy 1.19.5
- pandas 1.1.5
- Pillow 8.4.0
- pip 21.3.1
- protobuf 3.19.6
- pyparsing 3.0.9
- python-dateutil 2.8.2
- pytz 2023.3
- PyYAML 6.0
- scipy 1.5.4
- setuptools 36.4.0
- six 1.16.0
- sumolib 1.17.0
- tensorboard 1.11.0
- tensorflow 1.11.0
- termcolor 1.1.0
- torch 1.5.0
- tqdm 4.59.0
- traci 1.17.0
- typing_extensions 4.1.1
- Werkzeug 2.0.3
- wheel 0.37.1
- zipp 3.6.0

I hope this helps! If you have any further questions about these packages, please feel free to ask.

Best regards.

**Comment by way-thu** [comment]
> Hello,
> 
> Thanks for reaching out! Here is my Python package list:
> 
> * absl-py 1.4.0
> * astor 0.8.1
> * certifi 2020.6.20
> * cycler 0.11.0
> * dataclasses 0.8
> * decorator 4.4.2
> * eclipse-sumo 1.14.0
> * future 0.18.3
> * gast 0.5.4
> * grpcio 1.48.2
> * h5py 2.10.0
> * importlib-metadata 4.8.3
> * Keras 2.1.0
> * Keras-Applications 1.0.8
> * Keras-Preprocessing 1.1.2
> * kiwisolver 1.3.1
> * libsumo 1.16.0
> * Markdown 3.3.7
> * matplotlib 3.3.4
> * networkx 2.5.1
> * numpy 1.19.5
> * pandas 1.1.5
> * Pillow 8.4.0
> * pip 21.3.1
> * protobuf 3.19.6
> * pyparsing 3.0.9
> * python-dateutil 2.8.2
> * pytz 2023.3
> * PyYAML 6.0
> * scipy 1.5.4
> * setuptools 36.4.0
> * six 1.16.0
> * sumolib 1.17.0
> * tensorboard 1.11.0
> * tensorflow 1.11.0
> * termcolor 1.1.0
> * torch 1.5.0
> * tqdm 4.59.0
> * traci 1.17.0
> * typing_extensions 4.1.1
> * Werkzeug 2.0.3
> * wheel 0.37.1
> * zipp 3.6.0
> 
> I hope this helps! If you have any further questions about these packages, please feel free to ask.
> 
> Best regards.

Much appreciate！ I will try later and hope to solve it.  Thanks for your reply again.
